#!/bin/bash
# =============================================================================
# openSUSE AI Assistant - JeOS First-Boot Module (04_ai_assistant.sh)
# Platform: openSUSE Leap 16 (Agama installer, not YaST firstboot)
# Runs during first boot to set up the AI assistant stack
# Location: /etc/firstboot.d/scripts/04_ai_assistant.sh
# Triggered by: systemd-firstboot or Agama post-install
# =============================================================================
set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log_info() { echo -e "${GREEN}[firstboot]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[firstboot]${NC} $1"; }
log_error() { echo -e "${RED}[firstboot]${NC} $1"; }

# ─── Determine the real user (not root during firstboot) ───
# firstboot scripts run as root; we need the actual user for later steps
REAL_USER=""
REAL_GROUP=""

# On Agama (Leap 16), the user is created during install
# On YaST firstboot (Leap 15), user may not exist yet
if [[ -n "${SUDO_USER:-}" ]]; then
    REAL_USER="${SUDO_USER}"
elif [[ "${EUID}" -eq 0 ]] && id -u "opensuse" &>/dev/null; then
    REAL_USER="opensuse"
else
    REAL_USER="$(awk -F: '$3 >= 1000 && $3 < 65534 {print $1; exit}' /etc/passwd 2>/dev/null || echo "")"
fi

if [[ -z "${REAL_USER}" ]]; then
    log_warn "No regular user detected yet. Skipping user-specific setup."
    log_info "Run 'sudo ./install.sh' after creating your user account."
fi

REAL_GROUP="$(id -gn "${REAL_USER}" 2>/dev/null || echo "users")"
log_info "Target user: ${REAL_USER:-root}:${REAL_GROUP}"

# ─── Detect Platform ───
OS_ID=""
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    OS_ID="${ID:-unknown}"
    OS_VERSION="${VERSION_ID:-unknown}"
fi

# Detect Agama (Leap 16) vs YaST firstboot (Leap 15)
IS_AGAMA=false
IS_YAST_FIRSTBOOT=false

if command -v agama &>/dev/null || [[ -d /usr/share/agama ]] || [[ "${OS_VERSION%%.*}" -ge 16 ]]; then
    IS_AGAMA=true
    log_info "Detected: Agama installer / Leap 16"
elif systemctl is-enabled --quiet firstboot 2>/dev/null; then
    IS_YAST_FIRSTBOOT=true
    log_info "Detected: YaST firstboot"
else
    log_info "Detected: Standard post-install"
fi

# ─── Step 1: System packages ───
log_info "Installing system packages..."

# Python 3.13 (default on Leap 16)
if ! rpm -q python313 &>/dev/null 2>&1; then
    zypper --non-interactive --no-gpg-checks install -y python313 python313-pip python313-base
fi

# Podman (preferred container engine)
if ! rpm -q podman &>/dev/null 2>&1; then
    zypper --non-interactive --no-gpg-checks install -y podman podman-docker buildah
fi

# Enable podman socket (rootless)
systemctl enable --now podman.socket 2>/dev/null || true

# ─── Step 2: uv package manager ───
if [[ -n "${REAL_USER}" ]] && [[ "${REAL_USER}" != "root" ]]; then
    if ! sudo -u "${REAL_USER}" command -v uv &>/dev/null; then
        log_info "Installing uv for user ${REAL_USER}..."
        sudo -u "${REAL_USER}" bash -c 'curl -LsSf https://astral.sh/uv/install.sh | CARGO_HOME="$HOME/.cargo" sh'
    fi
fi

# Also install uv system-wide for root operations
if ! command -v uv &>/dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | CARGO_HOME=/root/.cargo sh
    export PATH="/root/.cargo/bin:${PATH:-}"
fi

# ─── Step 3: Create directories ───
log_info "Creating application directories..."
mkdir -p /var/lib/suse-ai/{models,index,cache/docs,state,logs}

if [[ -n "${REAL_USER}" ]]; then
    chown -R "${REAL_USER}:${REAL_GROUP}" /var/lib/suse-ai
else
    chown -R root:root /var/lib/suse-ai
fi

# ─── Step 4: Default configuration ───
CONFIG_FILE="/var/lib/suse-ai/state/config.yaml"
if [[ ! -f "${CONFIG_FILE}" ]]; then
    log_info "Creating default configuration..."
    cat > "${CONFIG_FILE}" <<'CONFIG'
# openSUSE AI Assistant - Configuration
# Generated by firstboot module

llm:
  base_url: "http://localhost:8080/v1"
  model: "/var/lib/suse-ai/models/LFM2.5-1.2B-Instruct-Q4_K_M.gguf"
  port: 8080
  threads: 4
  ctx_size: 8192
  n_gpu_layers: 0  # Set to -1 for full GPU offload

app:
  port: 8090
  host: "0.0.0.0"

rag:
  enabled: true
  backend: "chromadb"  # chromadb | qdrant
  cache_dir: "/var/lib/suse-ai/cache/docs"
  index_dir: "/var/lib/suse-ai/index"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"

container:
  engine: "podman"  # podman | docker
  image: "suse-ai:latest"
CONFIG
    if [[ -n "${REAL_USER}" ]]; then
        chown "${REAL_USER}:${REAL_GROUP}" "${CONFIG_FILE}"
    fi
    chmod 600 "${CONFIG_FILE}"
fi

# ─── Step 5: Install Python dependencies ───
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Look for requirements.txt relative to this script or common install locations
REQUIREMENTS_FILE=""
for candidate in \
    "${SCRIPT_DIR}/../../requirements.txt" \
    "/opt/suse-ai-deploy/requirements.txt" \
    "/usr/share/suse-ai/requirements.txt"; do
    if [[ -f "${candidate}" ]]; then
        REQUIREMENTS_FILE="${candidate}"
        break
    fi
done

if [[ -n "${REQUIREMENTS_FILE}" ]]; then
    log_info "Installing Python dependencies from ${REQUIREMENTS_FILE}..."
    uv pip install --system -r "${REQUIREMENTS_FILE}" 2>/dev/null || \
        python3.13 -m pip install --no-cache-dir -r "${REQUIREMENTS_FILE}" 2>/dev/null || \
        log_warn "Failed to install Python dependencies. Run: uv pip install -r requirements.txt"
else
    log_warn "requirements.txt not found. Python deps not installed."
fi

# ─── Step 6: Systemd units ───
log_info "Setting up systemd services..."

# Only install systemd units if NOT running in a container
if [[ ! -f /.dockerenv ]] && ! grep -qE '(docker|lxc|containerd)' /proc/1/cgroup 2>/dev/null; then
    # Install Podman quadlet units (do NOT hardcode User= — let Podman use current user)
    QUADLET_DIR="/etc/containers/systemd"
    mkdir -p "${QUADLET_DIR}"

    # Copy quadlet files from deploy/podman/ if they exist
    if [[ -d "${SCRIPT_DIR}/../podman" ]]; then
        cp "${SCRIPT_DIR}/../podman/suse-ai.container" "${QUADLET_DIR}/" 2>/dev/null || true
        cp "${SCRIPT_DIR}/../podman/suse-ai.service" "${QUADLET_DIR}/" 2>/dev/null || true
        cp "${SCRIPT_DIR}/../podman/suse-ai.socket" "${QUADLET_DIR}/" 2>/dev/null || true
        log_info "Quadlet units installed to ${QUADLET_DIR}/"
    fi

    systemctl daemon-reload 2>/dev/null || true
else
    log_info "Running inside a container — skipping systemd setup"
fi

# ─── Step 7: Firstboot marker ───
MARKER_FILE="/var/lib/suse-ai/state/.firstboot-complete"
date -Iseconds > "${MARKER_FILE}"
if [[ -n "${REAL_USER}" ]]; then
    chown "${REAL_USER}:${REAL_GROUP}" "${MARKER_FILE}"
fi

# ─── Done ───
echo ""
log_info "openSUSE AI Assistant first-boot setup complete!"
echo ""
log_info "Next steps:"
echo "  1. Download models:    ./scripts/download_models.sh"
echo "  2. Build container:    ./scripts/build_podman.sh"
echo "  3. Start services:     podman compose up -d"
echo "  4. Access AI assistant: http://localhost:8090"
echo ""
