apiVersion: v1
kind: Namespace
metadata:
  name: ai-assistant
  labels:
    app.kubernetes.io/name: ai-assistant
    app.kubernetes.io/instance: ai-assistant
    app.kubernetes.io/part-of: suse-ai-deploy
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: ai-platform
    environment: production
    team: ai-infra
